name: Web
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: ⚙️ Set up repository
        uses: actions/checkout@v2
      
      - name: ❇️ Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16.x

      - name: 🔷 Install Expo CLI
        run: npm install -g expo-cli

      - name: 📦 Install dependencies
        run: npm install

      - name: 🌐 Export the app
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          yarn deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
